services:
  backend:
    build: ./backend
    container_name: lemon-backend
    ports:
      - "5000:5000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./backend/scripts:/app/scripts
    depends_on:
      - db
      - init-db

  frontend:
    build: ./frontend
    container_name: lemon-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  init-db:
    build: ./backend
    command: python /app/scripts/initialise_tables.py
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
